name: omra_truck
description: Application guide Omra Truck – Version Pro (Offline, BLE, Santé, Multilingue)
version: 2.0.0+2
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.5
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  go_router: ^14.0.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.0
  speech_to_text: ^7.0.0
  adhan_dart: ^1.1.1
  flutter_blue_plus: ^1.31.2
  share_plus: ^12.0.0 # Corrigé pour résoudre le conflit avec speech_to_text
  url_launcher: ^6.3.0
  pedometer: ^4.0.0
  vibration: ^2.0.0
  fl_chart: ^0.68.0
  animated_text_kit: ^4.2.2
  # Dépendances essentielles
  timezone: ^0.9.2
  connectivity_plus: ^5.0.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2 # Maintenu à la version requise par flutter_localizations
  battery_plus: ^4.0.2
  device_info_plus: ^9.1.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_map_marker_cluster: ^1.0.0
  # Pour le QR code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.0
  # Pour le BLE
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/images/
    - assets/map_tiles/